In [23]:
import pandas as pd
import numpy as np
from sklearn import linear_model

### House prices dataset

In [18]:
df1=pd.read_csv('home_prices.csv')
df1

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [19]:
df1.bedrooms.fillna(df1.bedrooms.median(),inplace=True)
df1.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [20]:
alg1=linear_model.LinearRegression()

In [24]:
alg1.fit(df1.drop('price',axis=1).values,df1.price)

LinearRegression()

In [25]:
alg1.coef_,alg1.intercept_

(array([  112.06244194, 23388.88007794, -3231.71790863]), 221323.00186540443)

###### predicting house price for 3000 sq-ft,3 bedroom,40 yr-old

In [26]:
alg1.predict([[3000,3,40]])

array([498408.25158031])

###### predicting house price for  2500 sq-ft,4 bedroom,5 yr-old

In [27]:
alg1.predict([[2500,4,5]])

array([578876.03748933])

### Hiring candidate salary dataset

In [71]:
df2=pd.read_csv('hired.csv')
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [72]:
df2.experience.fillna('zero',inplace=True)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [73]:
from word2number import w2n

In [74]:
df2.experience=df2.experience.apply(w2n.word_to_num)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [75]:
import math
df2['test_score(out of 10)'].fillna(math.floor(df2['test_score(out of 10)'].mean()),inplace=True)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [76]:
alg2=linear_model.LinearRegression()

In [77]:
alg2.fit(df2.drop('salary($)',axis=1).values,df2['salary($)'])

LinearRegression()

In [78]:
alg2.coef_,alg2.intercept_

(array([2922.26901502, 2221.30909959, 2147.48256637]), 14992.651446693148)

##### predicting for 2 yr experience, 9 test score, 6 interview score

In [79]:
alg2.predict([[2,9,6]])

array([53713.86677124])

##### predicting for 12 yr experience, 10 test score, 10 interview score

In [81]:
alg2.predict([[12,10,10]])

array([93747.79628651])

###### custom function to convert words to number(trying)

In [48]:
# defining our own function in this case is lengthy so we will use the python word2number library
# def func(cell):
#     if cell=='zero':
#         return 0
#     elif cell=='one':
#         return 1
#     elif cell=='two':
#         return 2
#     elif cell=='three':
#         return 3
#     elif cell=='four':
#         return 4
#     elif cell=='five':
#         return 5
#     elif cell=='six':
#         return 6
#     elif cell=='seven':
#         return 7
#     elif cell=='eight':
#         return 8
#     elif cell=='nine':
#         return 9
#     elif cell=='ten':
#         return 10
#     elif cell=='eleven':
#         return 11

In [45]:
# df2.experience.apply(func)

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64